package com.unicamp.mc322.Cartas.Efeitos;

public enum TipoDeEfeito {
	
	ATAQUE_DEFESA_DOBRADO, PODER_VIDA_UNIDADES_ALIADAS, PODER_VIDA_UMA_ALIADA, VIDA_TOTALMENTE_CURADA,
	ATAQUE_NEXUS_ADVERSARIO, ATAQUE_N_DANO_NEXUS, COMBATE_IMEDIATO, ATACANTE_GOLPEIA_TODOS_OPONENTES,
	PODER_ADVERSARIO_ZERADO, NOVA_CARTA_APOS_DESTRUIDA
	
}
